version: '2'
services:
    web:
        container_name: bdd_web_1
        build: docker/nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        depends_on:
            - db
            - php

    db:
        container_name: bdd_db_1
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bdd-behat
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes_from:
            - db-data
        depends_on:
            - db-data

    db-data:
        container_name: bdd_dbdata_1
        image: busybox:latest
        volumes:
            - ./var/lib/mysql:/var/lib/mysql

    php:
        container_name: bdd_php_1
        build: docker/php-fpm
        volumes:
            - .:/app
        links:
            - db
